# Generated by Django 3.1.1 on 2020-09-28 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Captains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=70)),
                ('player_notes', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SquadInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squad_name', models.CharField(max_length=50)),
                ('shirt_design', models.IntegerField(null=True)),
                ('shirt_colors', models.CharField(max_length=13, null=True)),
                ('captain_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.captains')),
            ],
        ),
        migrations.CreateModel(
            name='TeamInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('formation', models.CharField(max_length=5)),
                ('squad_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.squadinfo')),
            ],
        ),
        migrations.CreateModel(
            name='TeamPlayers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=5)),
                ('player_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.playerinfo')),
                ('team_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.teaminfo')),
            ],
        ),
        migrations.AddField(
            model_name='playerinfo',
            name='squad_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.squadinfo'),
        ),
        migrations.CreateModel(
            name='MatchReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opposition', models.CharField(max_length=40)),
                ('message', models.CharField(max_length=1000)),
                ('final_score', models.CharField(max_length=5)),
                ('result', models.CharField(max_length=4)),
                ('captain_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.captains')),
            ],
        ),
    ]
