# Generated by Django 3.1.1 on 2020-09-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opposition', models.CharField(max_length=40)),
                ('message', models.CharField(max_length=1000)),
                ('final_score', models.CharField(max_length=5)),
                ('result', models.CharField(max_length=4)),
            ],
        ),
    ]
