# Generated by Django 3.1.1 on 2020-09-30 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_captains_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerinfo',
            name='squad_id',
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=70)),
                ('player_notes', models.CharField(max_length=1000)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='matchreport',
            name='captain_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.players'),
        ),
        migrations.AlterField(
            model_name='squadinfo',
            name='captain_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.players'),
        ),
        migrations.AlterField(
            model_name='teamplayers',
            name='player_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.players'),
        ),
        migrations.DeleteModel(
            name='Captains',
        ),
        migrations.DeleteModel(
            name='PlayerInfo',
        ),
    ]
