# Generated by Django 3.1.1 on 2020-09-28 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_matchreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchreport',
            name='captain_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.captains'),
        ),
    ]
