# Generated by Django 3.1.1 on 2020-09-28 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200928_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchreport',
            name='captain_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.captains'),
        ),
    ]
