# Generated by Django 3.1.1 on 2020-09-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_players_player_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='player_notes',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
