# Generated by Django 3.1.1 on 2020-09-30 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0005_players_player_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchreport',
            name='captain_id',
        ),
        migrations.RemoveField(
            model_name='teaminfo',
            name='squad_id',
        ),
        migrations.AddField(
            model_name='matchreport',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teamplayers',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamplayers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teaminfo',
            name='formation',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='teamplayers',
            name='position',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='SquadInfo',
        ),
    ]
