# Generated by Django 3.1.1 on 2020-09-28 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200928_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=70)),
                ('player_notes', models.CharField(max_length=1000)),
                ('captain_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.captains')),
            ],
        ),
        migrations.CreateModel(
            name='TeamInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('formation', models.CharField(max_length=5)),
                ('captain_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.captains')),
            ],
        ),
        migrations.CreateModel(
            name='TeamPlayers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=5)),
                ('captain_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.captains')),
                ('player_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.playerinfo')),
                ('team_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.teaminfo')),
            ],
        ),
        migrations.CreateModel(
            name='SquadInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squad_name', models.CharField(max_length=50)),
                ('shirt_design', models.IntegerField(null=True)),
                ('shirt_colors', models.CharField(max_length=13, null=True)),
                ('captain_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.captains')),
            ],
        ),
    ]
