# Generated by Django 3.1.1 on 2020-09-30 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200930_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchreport',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.teaminfo'),
        ),
    ]
