# Generated by Django 3.1.1 on 2020-09-28 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200928_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamplayers',
            name='captain_id',
        ),
        migrations.AddField(
            model_name='teamplayers',
            name='squad_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.squadinfo'),
        ),
    ]
