# Generated by Django 3.1.1 on 2020-09-30 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_matchreport_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchreport',
            name='team_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.teaminfo'),
        ),
    ]
