# Generated by Django 3.1.1 on 2020-09-28 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20200928_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamplayers',
            name='squad_id',
        ),
    ]
