# Generated by Django 3.1.1 on 2020-09-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_matchreport_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminfo',
            name='player1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='player10',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='player11',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='player2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='player3',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='player4',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='player5',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='player6',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='player7',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='player8',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='player9',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teaminfo',
            name='team_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
