# Generated by Django 3.1.1 on 2020-09-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20200930_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teaminfo',
            old_name='player1',
            new_name='position1',
        ),
        migrations.RenameField(
            model_name='teaminfo',
            old_name='player10',
            new_name='position10',
        ),
        migrations.RenameField(
            model_name='teaminfo',
            old_name='player11',
            new_name='position11',
        ),
        migrations.RenameField(
            model_name='teaminfo',
            old_name='player2',
            new_name='position2',
        ),
        migrations.RenameField(
            model_name='teaminfo',
            old_name='player3',
            new_name='position3',
        ),
        migrations.RenameField(
            model_name='teaminfo',
            old_name='player4',
            new_name='position4',
        ),
        migrations.RenameField(
            model_name='teaminfo',
            old_name='player5',
            new_name='position5',
        ),
        migrations.RenameField(
            model_name='teaminfo',
            old_name='player6',
            new_name='position6',
        ),
        migrations.RenameField(
            model_name='teaminfo',
            old_name='player7',
            new_name='position7',
        ),
        migrations.RenameField(
            model_name='teaminfo',
            old_name='player8',
            new_name='position8',
        ),
        migrations.RenameField(
            model_name='teaminfo',
            old_name='player9',
            new_name='position9',
        ),
        migrations.AlterField(
            model_name='teaminfo',
            name='formation',
            field=models.CharField(max_length=20),
        ),
    ]
