# Generated by Django 3.1.1 on 2020-10-01 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20200930_2248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamPlayers',
        ),
    ]
